### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by ThomasHaine**
I've made many cosmetic changes to the UI and tried to enhance usability of the viewer. There are still some things I want to change, including instructions on how to use the tools etc. But that can wait for another issue. There are also two bugs that I need help fixing (both to do with the time stamp controls). Meanwhile, please take a look and give feedback etc.

### CODE REVIEW

**Comment by MaceKuailv** [comment]
A small problem: the notebook is not converted to markdown in the correct way. 
Use: `jupytext --to myst filename.ipynb`, you will need to `pip install jupytext` first

**Comment by MaceKuailv** [comment]
Yeah, the run failed because of the header.

**Comment by ThomasHaine** [comment]
OK, I rebuilt the `create_interpolator_for_LLC.md` markdown with `jupytext`. Please check again.

**Comment by MaceKuailv** [comment]
all tests are passing. I will merge

**Pull request merged**
